import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container:{
        width:393,
        height:853,
        backgroundColor:'#FFFFFF',
    },
    header:{
        width:393,
        height:200,
        backgroundColor:'#6655D0',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },
    information:{
        flexDirection: 'row',
        alignItems: 'center',
    },
    profile:{
        width:240,
        height:20,
        fontFamily:'Roboto',
        fontSize:18,
        color: '#FFFFFF',
        right:36,
        marginTop:10,
    },
    notifications:{
        width:24,
        height:24,
        left:26,
        marginTop:10,
    },
    settings:{
        width:24,
        height:24,
        marginRight:'auto',
        left:36,
        marginTop:10,

    },
    account:{
        marginTop:24,
        flexDirection: 'row',
        alignItems: 'center',
    },
    avata:{
        width:108,
        height:108,
        marginTop:24,
        marginEnd:24,
        left:56,
    },
    camera:{
        width:28,
        height:28,
        marginTop:97,
        color:'#FFFFFF',
        marginEnd:31,
    },
    heading:{
        width:119,
        height:45,
        marginTop:54,
        marginEnd:45,
        right:15,
    },
    heading1:{
        width:129,
        height:21,
        fontFamily:'Roboto',
        fontSize:18,
        lineHeight:21,
        textAlign: 'center',
        color:'#FFFFFF',
    },
    heading2:{
        width:81,
        height:18,
        fontFamily: 'Roboto',
        fontSize:15,
        lineHeight:17,
        textAlign: 'center',
        color:'#EDEDED',
    },
    button1:{
        width:85,
        height:27,
        backgroundColor:'#FFFFFF',
        borderRadius:12,
        textAlign: 'center',
        fontFamily:'Roboto',
        fontSize:14,
        color:'#391085',
        textShadowOffset: { width: 40, height:16 }, 
        fontWeight:'bold',
        marginEnd:54,
        marginTop:35,
        right:15,
    },
    main:{
        width:393,
        height:100,
        backgroundColor:'#FFFFFF',
        flexDirection: 'row',
        alignItems: 'center',
        marginTop:8,
    },
    Profile_user:{
        width:70,
        height:76,
        marginLeft:16,
        marginRight:16,
    },
    User:{
        width:46,
        height:48,
        borderRadius:6,
        marginLeft:12,
        marginRight:12,
    },
    main_heading1:{
        width:68,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        lineHeight:14,
        textAlign: 'center',
        color:'#391085',
    },
    Discount:{
        width:48,
        height:48,
        borderRadius:6,
        marginLeft:11,
        marginRight:11,
    },
    main_heading2:{
        width:68,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        lineHeight:14,
        textAlign: 'center',
        color:'#391085',
    },
    Profile_Accumulation:{
        width:94,
        height:76,
    },
    accumulation:{
        width:48,
        height:48,
        borderRadius:6,
        marginLeft:23,
        marginRight:23,
    },
    main_heading3:{
        width:92,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        lineHeight:14,
        textAlign: 'center',
        color:'#391085',
    },

    approve:{
        width:46,
        height:48,
        borderRadius:6,
        marginLeft:12,
        marginRight:12,
    },
    main_heading4:{
        width:68,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        textAlign: 'center',
        color:'#391085',
    },
    body:{
        width:393,
        height:128,
        borderRadius:4,
        marginTop:4,
    },
    body_body:{
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft:16,
        marginRight:16,
        marginTop:12,
    },
    body_header:{
        width:134,
        height:28,
        marginLeft:16,
        marginRight:243,
        marginTop:4,
        fontWeight:'bold',
    },
    Subordinate_account:{
        width:124,
        height:16,
        fontFamily:'Roboto',
        fontSize:14,
        lineHeight:16,
        textAlign:'center',
        color:'#000000',
    },
    body_rose:{
        width:74,
        height:76,
        marginEnd:12,
        marginLeft:16,
        marginRight:24,
    },
    Rose:{
        width:48,
        height:48,
        marginLeft:13,
        marginRight:13,
    },
    body_heading1:{
        width:74,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        lineHeight:14,
        textAlign:'center',
        color:'#391085',
    },
    body_Loyal:{
        width:74,
        height:76,
        marginRight:24,
        marginEnd:12,
    },
    Loyal_customers:{
        width:48,
        height:48,
        borderRadius:6,
        marginLeft:13,
        marginRight:13,
    },
    body_heading2:{
        width:74,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        lineHeight:14,
        textAlign:'center',
        color:'#391085'
    },
    body_Link:{
        width:74,
        height:76,
        marginRight:91,
        marginLeft:24,
    },
    Link:{
        width:48,
        height:48,
        borderRadius:6,
        marginLeft:13,
        marginRight:13,
    },
    body_heading3:{
        width:74,
        height:28,
        fontFamily:'Roboto',
        fontSize:12,
        lineHeight:14,
        textAlign:'center',
        color:'#391085',
    },
    Hotline:{
        marginTop:107,
        marginLeft:317,
        marginRight:16,
        marginEnd:210,
    },
    Logout:{
        width:361,
        height:48,
        borderRadius:8,
        backgroundColor:'#EB2F96',
        marginLeft:16,
        marginRight:16,
        marginTop:40,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center', 
        textAlign: 'center', 
    },
    Logout_heading:{
        width:73,
        height:22,
        fontFamily:'Roboto',
        fontSize:16,
        lineHeight:22,
        textAlign:'center',
        color:'#FFFFFF',
        alignItems: 'center',
    },
});

export default styles;
